model:
  class: "contact_graspnet.models.ContactGraspnet"
  config_path: "~/Documents/ContactGraspnetBenchmark/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001/config.yaml"
  checkpoint_dir: "~/Documents/ContactGraspnetBenchmark/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001"

preprocessor:
  class: "contact_graspnet.preprocessing.YCBSimulationPreprocessor"
  z_clipper:
    class: "contact_graspnet.preprocessing.ZClipper"
    z_range: [0.2, 1.8]
  segmenter:
    class: "contact_graspnet.preprocessing.YCBDepthBoxSegmenter"
    depth2pc_converter: 
      class: "contact_graspnet.preprocessing.OrigDepth2Points"
    margin: 30

postprocessor:
  class: "contact_graspnet.postprocessing.Postprocessor"
  top_score_filter: null 
    # class: "contact_graspnet.postprocessing.TopSoreFilter"
    # top_k: 3 